### ISSUE TITLE
Uncaught exception: app.adaptToSystemTheme is not a function

### ISSUE THREAD

**Issue by baodrate** [pjeby/pane-relief#60]
with obsidian v1.7.5 and pane-relief v0.5.5, I get the following exception when toggling the system dark mode setting

```stacktrace
Navigator.ts:43 Uncaught TypeError: app.adaptToSystemTheme is not a function
    at MediaQueryList.eval (Navigator.ts:43:56)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
```

**Comment by pjeby** [comment]
It looks like somewhere in the 1.7.x line the theme adaption mechanism was changed.  Pane Relief has a workaround for earlier Obsidian versions not actually adapting the theme, so it's failing here.  The error is harmless, but I will update Pane Relief so it doesn't do that any more.  Thanks for reporting this!

**Comment by pjeby** [comment]
(The original issue was in 1.5.x, and apparently fixed somewhere in the 1.6.x range: https://forum.obsidian.md/t/detached-window-doesnt-change-color-scheme-automatically/42642/10 )

**Comment by pjeby** [comment]
This is now fixed in 0.5.7
